FROM node:14 AS app-init

ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV PATH="/home/node/.npm-global/bin:${PATH}"

RUN npm install -g @angular/cli

WORKDIR /usr/src/app/

COPY package.json .
COPY package-lock.json .

RUN npm install

FROM app-init AS app-dev

WORKDIR /usr/src/app
EXPOSE 4400
# Tilt will handle updates to these files, and rebuild when needed, but hot swap
# when it can
COPY . .

WORKDIR /usr/src/app/

CMD ng serve --host 0.0.0.0 --port 4200 --disable-host-check --verbose