apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    type: local
spec:
  storageClassName: databases
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"
