apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-matrix-api
spec:
  selector:
    matchLabels:
      app: skill-matrix-api
  replicas: 4
  template:
    metadata:
      labels:
        name: skill-matrix-api
        app: skill-matrix-api
    spec:
      volumes:
        - name: api-sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-volume-claim
      containers:
        - name: skill-matrix-api
          image: skill-matrix-api-image
          ports:
            - name: api-port
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/status
              port: api-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/status
              port: api-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
          volumeMounts:
            - mountPath: /mnt/data
              name: api-sqlite-volume
      initContainers:
        - name: skill-matrix-api-migrater
          image: skill-matrix-api-image
          command: ["python", "/usr/src/skill_matrix_api/manage.py", "migrate"]
