apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skill-matrix-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skill-matrix-api
  minReplicas: 4
  maxReplicas: 100
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 5
          periodSeconds: 10
    scaleUp:
      policies:
        - periodSeconds: 10
          type: Pods
          value: 5
      
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

